### ISSUE TITLE
Bug mauvais identifiants login

### ISSUE THREAD

**Issue by ghost** [snap-project/snap#2]
Si l'on tente d'utiliser la méthode login() de l'API users avec de mauvais identifiants, le serveur remonte une erreur puis se coupe.

``` bash
# erreur remontée
{
 "name":"snap",
 "hostname":"workspace",
 "pid":12151,
 "level":60,
 "err":{
    "message":"undefined is not a function",
    "name":"TypeError",
    "stack": "TypeError: undefined is not a function\n 
         at UsersDefaultBackend.onStoreResult (/home/ben/Workspace/snap/lib/api/users/default-backend.js:110:17) 
         at dispatchError (/home/ben/Workspace/snap/node_modules/levelup/lib/util.js:131:7)
         at /home/ben/Workspace/snap/node_modules/levelup/lib/levelup.js:197:14  
         at /home/ben/Workspace/snap/node_modules/nedbDOWN/lib/nedbdown.js:47:16   
         at callback (/home/ben/Workspace/snap/node_modules/nedbDOWN/node_modules/nedb/lib/executor.js:30:17)
         at Cursor.execFn (/home/ben/Workspace/snap/node_modules/nedbDOWN/node_modules/nedb/lib/datastore.js:451:14)
         at Cursor._exec (/home/ben/Workspace/snap/node_modules/nedbDOWN/node_modules/nedb/lib/cursor.js:172:17)
         at /home/ben/Workspace/snap/node_modules/nedbDOWN/node_modules/nedb/lib/executor.js:40:13
         at Object.q.process [as _onImmediate] (/home/ben/Workspace/snap/node_modules/async/lib/async.js:731:21)
         at processImmediate [as _immediateCallback] (timers.js:345:15)"
  },
  "msg":"undefined is not a function",
  "time":"2014-12-23T09:49:06.546Z",
  "v":0
}
[TypeError: undefined is not a function]
```

**Comment by Bornholm** [comment]
Corrigé avec c80f2512524a9a84d45a4399064d0b838ef02e78
